### ISSUE TITLE
The 'or' operation doesn't seem to work

### ISSUE THREAD

**Issue by lburja** [leapfrogtechnology/just-handlebars-helpers#40]
I have this in my page:

{{log "The or operator: " (or false false)}}

And I get back:

The or operator:  true

which is obviously wrong.

If I register a new 'or' helper, where I check the hasOwnProperty then everything works fine:

            Handlebars.registerHelper('or', function () {
                var params =  Array.prototype.slice.call(arguments);
                if ((typeof params[params.length - 1] === 'object')) {
                    params.pop();
                }
			
                for (var index in params) {
                    if (params.hasOwnProperty(index) && params[index]) {
                        return true;
                    }
                }
			
                return false;
            });

The or operator:  false

**Comment by kabirbaidhya** [comment]
@lburja I just wrote a simple test for this helper and it's passing. 

```javascript
 +        it ('should work fine with direct boolean values', () => {
 +            var template = compile('{{concat "The or operator: " (or false false)}}');
 +
 +            expect(template()).toEqual('The or operator: false');
 +        });
```

https://travis-ci.org/leapfrogtechnology/just-handlebars-helpers/jobs/140717793#L1118-L1123

Can you tell me which version of handlebars are you using?

**Comment by lburja** [comment]
Ok, I know what went wrong. Our project defines some methods on
Array.prototype.

Here is a use case that reproduces the problem:

<!DOCTYPE html>
<html>
<head>
    <title>'or' operator test</title>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.js"
type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.js"
type="text/javascript"></script>
    <script src="https://raw.githubusercontent.com/leapfrogtechnology/just-handlebars-helpers/master/dist/h.js"
type="text/javascript"></script>

    <script>
        H.registerHelpers(Handlebars);

        Array.prototype.someMethod = function () {
            console.log("Some method defined on the array, like forEach etc.");
        }
    </script>
</head>
<body>

<script id="hbs-main" type="text/x-handlebars-template">
    <h1>Result is wrong:</h1>
    <div>(or false false): {{or false false}}</div>
</script>

<div id="main"></div>

<script>
    var source = $("#hbs-main").html();
    var template = Handlebars.compile(source);
    var context = {
    };
    var html = template(context);

    $('#main').html(html);
</script>

</body>
</html>

**Comment by kabirbaidhya** [comment]
@lburja Okay, we've just figured out the problem. We'll fix this shortly. 
Anyway Thanks for reporting this issue.

**Comment by mesaugat** [comment]
@lburja Issue has been fixed. Please use the latest build.
