### ISSUE TITLE
Automate README doc generation from doc blocks

### ISSUE THREAD

**Issue by kabirbaidhya** [leapfrogtechnology/just-handlebars-helpers#47]
We need a new npm script something like `npm run doc` to automatically generate the markdown and regenerate README using the doc blocks.

@sanjeevkpandit knows how to do it :smile:.

**Comment by mesaugat** [comment]
And our `JSDoc` is also not proper.

**Comment by kabirbaidhya** [comment]
Yes, need to make docblocks consistent too.

**Comment by mesaugat** [comment]
I don't think we need this.
