### ISSUE TITLE
Why some packages are located in devDependencies but required in the 'src'

### ISSUE THREAD

**Issue by lwyj123** [leapfrogtechnology/just-handlebars-helpers#63]
![image](https://user-images.githubusercontent.com/9214496/63504092-5a2d4200-c503-11e9-90d6-ce22dd0d9596.png)

![image](https://user-images.githubusercontent.com/9214496/63504129-716c2f80-c503-11e9-925c-c580709c11a7.png)

**Comment by mesaugat** [comment]
@lwyj123 We want users of our package to install all these dependencies themselves. We don't want to bundle any of these packages with `just-handlebars-helpers`. 

Either we can add these as `peerDependencies` or update the `README.md` to inform the users more clearly.

It is already mentioned in the README but is easy to miss out.

https://github.com/leapfrogtechnology/just-handlebars-helpers#datetime

**Comment by mesaugat** [comment]
We can definitely improve the `README`, please send in a PR if you are interested. Also, the currencyFormatter has this information missing.

Right now we only require these dependencies as `devDependency` to run our tests.
