### ISSUE TITLE
how to avoid conflicts with naming when we use variables inside with block helper?

### ISSUE THREAD

**Issue by 7iomka** [leapfrogtechnology/just-handlebars-helpers#66]
Hi.
From backend I received this data
```
{
count: '...'',
hasResult: true,
query: '123', // input value
}
```
and my template is something like this
```
{{#with this}}
	{{#if hasResult}}
		For your query <strong>"{{query}}"</strong> found <strong>{{count}} peoples</strong>
	{{else}}
		Peoples not found
	{{/if}}
{{/with}}
```

I spent a lot of time trying to understand why instead of the value, a lie is returned to me before I realized that I connected your package with helper that have same name as "count".

How to avoid this with continue to use `with ` (I like to use direct variables comp. to this.someValue)
Thanks!

**Comment by mesaugat** [comment]
Hello @7iomka, sorry for the trouble. I've not looked at `handlebars` for a while but I think we can set a context like this.

```
{{#with this as |data|}}
        {{#if data.hasResult}}
		For your query <strong>"{{data.query}}"</strong> found <strong>{{data.count}} peoples</strong>
	{{else}}
		Peoples not found
	{{/if}}
{{/with}}
```

Can you check if this works for you?

**Comment by 7iomka** [comment]
> Hello @7iomka, sorry for the trouble. I've not looked at `handlebars` for a while but I think you can set a context like this.
> 
> ```
> {{#with this as |data|}}
>         {{#if data.hasResult}}
> 		For your query <strong>"{{data.query}}"</strong> found <strong>{{data.count}} peoples</strong>
> 	{{else}}
> 		Peoples not found
> 	{{/if}}
> {{/with}}
> ```
> 
> Can you check if this works for you?

yes it is logical that if you use dot notation it will work as in the case of using this notation, but my question is how to prevent name conflicts when the user directly uses the context? Well, or at least understand that the cause of the error is a name conflict?
It is very difficult to understand right away
